# Generated by Django 3.2.6 on 2021-08-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210825_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='cars/images/')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.car')),
            ],
        ),
    ]
