# Generated by Django 3.2.6 on 2021-09-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_morecarimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('customer_need', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('car_title', models.TextField(max_length=100)),
                ('car_id', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
